import { Award, Droplet, Gift, Heart, Sparkles, Trophy, Zap } from "lucide-react";

export const achievements = [
	{
		id: 1,
		icon: <Trophy size={20}  />,
		category: "Collection",
		title: "Fish Collector",
		description: "Collect 30 different fish species",
		progress: { completed: 24, total: 30 },
		xp: 200,
		rewards: "500 Coins + Rare Fish Egg",
		completed: false,
	},
	{
		id: 2,
		icon: <Sparkles size={20} />,
		category: "Decoration",
		title: "Aquarium Designer",
		description: "Decorate your aquarium with 20 different items",
		progress: { completed: 15, total: 20 },
		xp: 150,
		rewards: "Premium Decoration Set",
		completed: false,
	},
	{
		id: 3,
		icon: <Heart size={20} />,
		category: "Breeding",
		title: "Master Breeder",
		description: "Successfully breed 10 different fish combinations",
		progress: { completed: 7, total: 10 },
		xp: 300,
		rewards: "Breeding Lab Upgrade",
		completed: false,
	},
	{
		id: 4,
		icon: <Droplet size={20} />,
		category: "Special",
		title: "Water Expert",
		description: "Maintain perfect water quality for 7 consecutive days",
		progress: { completed: 7, total: 7 },
		xp: 0,
		rewards: "Advanced Filter System",
		completed: true,
		completedDate: "Apr 12, 2025",
	},
	{
		id: 5,
		icon: <Zap size={20} />,
		category: "Special",
		title: "Fish Whisperer",
		description: "Reach maximum happiness with 5 different fish",
		progress: { completed: 5, total: 5 },
		xp: 0,
		rewards: "Special Food Collection",
		completed: true,
		completedDate: "Mar 20, 2025",
	},
	{
		id: 6,
		icon: <Gift size={20} />,
		category: "Special",
		title: "Treasure Hunter",
		description: "Find 15 hidden treasures in your aquarium",
		progress: { completed: 8, total: 15 },
		xp: 250,
		rewards: "Golden Treasure Chest Decoration",
		completed: false,
	},
	{
		id: 7,
		icon: <Heart size={20} />,
		category: "Social",
		title: "Social Butterfly",
		description: "Make 10 friends in the Aqua Stark community",
		progress: { completed: 4, total: 10 },
		xp: 100,
		rewards: "Exclusive Social Profile Frame",
		completed: false,
	},
	{
		id: 8,
		icon: <Award size={20} />,
		category: "Collection",
		title: "Legendary Collector",
		description: "Collect 5 legendary fish species",
		progress: { completed: 2, total: 5 },
		xp: 500,
		rewards: "Legendary Fish Food + 1,000 Coins",
		completed: false,
	},
];
